export { default as Facebook } from './facebook'
export { default as Instagram } from './instagram'
export { default as Telegram } from './telegram'
export { default as Twitch } from './twitch'
export { default as Vk } from './vk'
export { default as Visa } from './visa'
export { default as Youtube } from './youtube'
export { default as Mastercard } from './mastercard'
