export { default as JS } from './js'
export { default as JsonSVG } from './json'
export { default as ReactSVG } from './react'
export { default as TS } from './ts'
export { default as TXT } from './txt'
export { default as FolderSVG } from './folder'
