export { default as over18 } from './over18'
export { default as peace } from './peace'
export { default as promotion } from './promotion'
export { default as reward } from './reward'
export { default as astronaut } from './astronaut'
export { default as camera } from './camera'
export { default as alcohol } from './alcohol'
